
import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./componentes/LayoutWrapper";

export const metadata: Metadata = {
  title: "Motiva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="min-h-screen flex flex-col">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
